In [142]:
import numpy as np
import pandas as pd

In [241]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [144]:
df


engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [145]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [146]:
#Q1. Pandas version : What version of Pandas did you install?
pd.__version__

'2.3.1'

In [273]:
#Q2. Records count : How many records are in the dataset?
9704 based on output of df

In [148]:
#Q3. Fuel types : How many fuel types are presented in the dataset?
df['fuel_type'].nunique()

2

In [149]:
#Q4. Missing values : How many columns in the dataset have missing values?
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [150]:
#Question 5. Max fuel efficiency : What's the maximum fuel efficiency of cars from Asia?
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

In [151]:
#Q6. Median value of horsepower : 

#1-    Find the median value of the horsepower column in the dataset.
#2-    Next, calculate the most frequent value of the same horsepower column.
#3-    Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
#4-    Now, calculate the median value of horsepower once again.

#Has it changed?

 #   Yes, it increased
 #   Yes, it decreased
 #   No


In [152]:
#1-Find the median value of the horsepower column in the dataset.
df['horsepower'].median()

np.float64(149.0)

In [153]:
#2-Next, calculate the most frequent value of the same horsepower column.

#To find the most frequent value (mode) in a pandas DataFrame column, you can use the mode() method.
df['horsepower'].mode()



0    152.0
Name: horsepower, dtype: float64

In [154]:
#To find out how many times the most frequent value appears, you can use the value_counts() method, 
df['horsepower'].value_counts().iat[0]

np.int64(142)

In [155]:
#3-Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
#to Fill Missing Values with the Mode
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode().iloc[0])

In [156]:
#4-Now, calculate the median value of horsepower once again.
df['horsepower'].median()

np.float64(152.0)

In [157]:
#we see the median has changed and it is increased

In [158]:
#Q7. Sum of weights


#1-    Select all the cars from Asia
#2-    Select only columns vehicle_weight and model_year
#3-    Select the first 7 values
#4-    Get the underlying NumPy array. Let's call it X.
#5-    Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#6-    Invert XTX.
#7-    Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
#8-    Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#9-    What's the sum of all the elements of the result?

#    Note: You just implemented linear regression. We'll talk about it in the next lesson.

#    0.051
#    0.51
#    5.1
#    51


In [243]:
#1-Select all the cars from Asia
df = df[df['origin'] == 'Asia']

In [244]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [245]:
#2-Select only columns vehicle_weight and model_year
df = df[['vehicle_weight', 'model_year']]

In [246]:
df

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [247]:
#3-Select the first 7 values
df = df.head(7)

In [248]:
df

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [249]:
#4-Get the underlying NumPy array. Let's call it X.


# Select only numeric columns
df_numeric = df.select_dtypes(include=['number'])

In [250]:
X = df_numeric.values  #X = df_numeric.to_numpy()

In [251]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [252]:
# Check total NaN values in your numeric array
print(f"Total NaN values in X: {np.isnan(X).sum()}")

# Check NaN values per column
print("NaN values per column:")
for i in range(X.shape[1]):
    nan_count = np.isnan(X[:, i]).sum()
    print(f"Column {i}: {nan_count} NaN values")

Total NaN values in X: 0
NaN values per column:
Column 0: 0 NaN values
Column 1: 0 NaN values


In [253]:
#🛠️ Methods to Handle NaN Values

#Here are several ways to replace NaN values in your NumPy array, from simplest to most sophisticated:
#Method	                    Best For	                                    Code Example
#Replace with Column Mean	General purpose, maintains data distribution	X = np.where(np.isnan(X), np.nanmean(X, axis=0), X)
#Replace with Zero	        Simple fix, when zero is meaningful	            X = np.nan_to_num(X, nan=0.0)
#Replace with Specific Value	Domain-specific replacements	            X = np.nan_to_num(X, nan=-999)
#Method 1: Replace NaN with Column Mean (Recommended)

In [254]:
#Method 1: Replace NaN with Column Mean (Recommended)

#This preserves the overall statistical properties of your data
# Vectorized approach using np.nanmean
col_means = np.nanmean(X, axis=0)  # Calculate mean for each column, ignoring NaN
inds = np.where(np.isnan(X))  # Find indices of all NaN values
X[inds] = np.take(col_means, inds[1])  # Replace NaN with corresponding column mean

In [255]:
#Method 2: Using np.nan_to_num()

#A simpler one-liner approach
# Replace NaN with 0 (be cautious - may distort your data)
#X = np.nan_to_num(X, nan=0.0)

# Or replace with a specific value that makes sense for your domain
#X = np.nan_to_num(X, nan=-999.0)

In [256]:
#Method 3: Using np.where() with Masked Array
#Another clean approach:
#X = np.where(np.isnan(X), np.ma.array(X, mask=np.isnan(X)).mean(axis=0), X)

In [257]:
#After cleaning your data, verify the result:
print(f"NaN values after cleaning: {np.isnan(X).sum()}")

NaN values after cleaning: 0


In [258]:
#5-Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

#method1: Using the .dot() method
import numpy as np
XTX = X.T.dot(X)
# Method 2: Using the @ operator (recommended)

#XTX = X.T @ X

# Method 3: Using np.dot()

#XTX = np.dot(X.T, X)

In [259]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [260]:
#6-Invert XTX.

XTX_inv = np.linalg.inv(XTX)

In [261]:
XTX_inv.shape

(2, 2)

In [262]:
X.T.shape

(2, 7)

In [263]:
#7-Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [264]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [265]:
#8-Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv.dot(X.T)

In [266]:
w.shape

(2, 7)

In [267]:
y.shape

(7,)

In [268]:
w = w.dot(y)
print(f"Result shape: {result.shape}")  # Should be (8,)

Result shape: (8,)


In [269]:
w

array([0.01386421, 0.5049067 ])

In [270]:
#9-What's the sum of all the elements of the result?
total_sum = np.sum(w)

In [271]:
total_sum

np.float64(0.5187709081074016)

In [272]:
#so the answer is 0.51